WORKFLOW_EVENT_TYPES = {
    "task.started": "task.started",
    "file.read": "file.read",
    "command.started": "command.started",
    "command.completed": "command.completed",
    "analysis.summary": "analysis.summary",
    "agent.planner.started": "agent.planner.started",
    "agent.planner.completed": "agent.planner.completed",
    "agent.executor.started": "agent.executor.started",
    "agent.executor.completed": "agent.executor.completed",
    "agent.reviewer.started": "agent.reviewer.started",
    "agent.reviewer.completed": "agent.reviewer.completed",
    "branch.created": "branch.created",
    "branch.selected": "branch.selected",
    "branch.reverted": "branch.reverted",
    "replan.requested": "replan.requested",
    "snapshot.created": "snapshot.created",
    "artifact.created": "artifact.created",
    "patch.applied": "patch.applied",
    "test.completed": "test.completed",
    "task.summarized": "task.summarized",
    "task.failed": "task.failed",
}
